### ISSUE TITLE
Do you need to use both simple and complex?

### ISSUE THREAD

**Issue by RickWillcox** [AgentFUD/agentfud-art-engine#21]
For example,

If I have a 
1 base body (that gets used for all)
3 helmets (red/blue/green)
3 gloves (red/blue/green)
3 t-shirts (red/blue/green)

What I want to do is generate all combinations
base + red helmet + red gloves + red t-shirt
base + red helmet + red glove + blue t-shirt
etc... I am a bit comfused about the complex / simple break down of layers. I tried putting no complex, and everything in simple like this
![image](https://user-images.githubusercontent.com/53924507/146629254-c0c1d9c5-1446-43a0-973b-fab08827a96d.png)

with the config like this
![image](https://user-images.githubusercontent.com/53924507/146629272-0fda9c94-4da6-4699-916b-b29aab7f01c9.png)

but that didnt work I get
![image](https://user-images.githubusercontent.com/53924507/146629274-0880f998-3df9-4b72-899b-44269cc76b0f.png)

Just not exactly sure how I should organize the folders for a task like this. Cheers!

**Comment by AgentFUD** [comment]
@RickWillcox complex layer is where a single layer is composed of multiple sprites. In your case you should not use complex layers. I invented the complex thingy as I wanted different tails and ears for all my cats. 
For example in the [layers](https://github.com/AgentFUD/layers) building a body requires three parts, a body, an ear and a tail. Because ears and tails are different, colouring them means I had to create all three shapes for coloring. I know it is a bit messy, I wanted to put together something working very fast. 

In theory if you leave complex_colors as an empty list in your instance_config.py, it should work with traditional single shaped designs. Feel free to suggest any solution. 

By the way, which version of the artengine are you using? Recently I pushed an update.

**Comment by AgentFUD** [comment]
Hi @RickWillcox , issue is fixed. Documentation is not updated, however if you create a new simple project **artengine init my-project --project-type simple" you should be fine. Documentation update and youtube video is coming.

**Comment by rickwillcox** [comment]
Thank you !
